title: "E-Plant Shopping"
description: "A platform for buying plants online"
baseurl: ""  # Leave empty for root-level hosting
url: "https://pruthvirajmashalkar.github.io/e-plantShopping"  # Correct URL for GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
