title: "E-Plant Shopping"
description: "A platform for buying plants online"
baseurl: "" # Leave empty if hosted at the root level of username.github.io
url: "https://github.com/PruthvirajMashalkar/e-plantShopping/settings/pages"  # Replace with your GitHub Pages URL
theme: jekyll-theme-primer  # Or any other theme you prefer
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Other settings, such as plugins or custom configurations, can go here.
